# ===============================
#  Basic
# ===============================
[[plugins]] # 非同期処理
repo = 'Shougo/vimproc.vim'
build = 'make -f make_mac.mak'

[[plugins]] # パッケージマネージャ
repo = 'Shougo/dein.vim'

[[plugins]] # ステータスライン
repo = 'itchyny/lightline.vim'
hook_add = '''
    let g:lightline = { 
    \   'colorscheme': 'default'
    \}
'''

#[[plugins]]
#repo = 'arcticicestudio/nord-vim'

[[plugins]] # スニペット・テンプレート
repo = 'Shougo/neosnippet-snippets'

[[plugins]] # Fuzzy Finder
repo = 'junegunn/fzf'
build = './install --all'
merged = '0'

[[plugins]] # Fuzzy Finder for Vim
repo = 'junegunn/fzf.vim'
depends = 'fzf'
 
# ===============================
#  LSP Client
# ===============================
[[plugins]] # LSP Client (Trial 1)
repo = 'autozimu/LanguageClient-neovim'
build = 'bash install.sh'
rev = 'next'

# ===============================
#  Lang
# ===============================
[[plugins]] # HTML5
repo  = 'othree/html5.vim'
on_ft = 'html'

[[plugins]] # CSS3
repo  = 'hail2u/vim-css3-syntax'
on_ft = 'css'

[[plugins]] # Javascript
repo  = 'jelera/vim-javascript-syntax'
on_ft = 'javascript'

[[plugins]] # Toml
repo  = 'cespare/vim-toml'
on_ft = 'toml'

#[[plugins]] # Markdown
#repo = 'rcmdnk/vim-markdown'
#on_ft = ['markdown','mkd']
#hook_add = '''
#    let g:vim_markdown_frontmatter = 1
#    let g:vim_markdown_math = 1
#'''

[[plugins]] # Golang
repo = 'fatih/vim-go'
on_ft = 'go'

# ===============================
#  For NeoVim Bug
# ===============================
[[plugins]] # rectangle paste
repo = 'bfredl/nvim-miniyank'
hook_add = '''
map p <Plug>(miniyank-autoput)
map P <Plug>(miniyank-autoPut)
'''
